# Generated by Django 4.2 on 2023-04-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNo', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('clinteId', models.CharField(blank=True, max_length=255, null=True)),
                ('deadLineDate', models.DateField()),
                ('procure_method', models.CharField(max_length=255)),
                ('tender_status', models.CharField(choices=[('Evaluated', 'Evaluated'), ('Bid Submission', 'Bid Submission'), ('Awarded', 'Awarded'), ('Canceled', 'Canceled')], max_length=255)),
                ('financial_value', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('winner', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenderCond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condOne', models.BooleanField(default=False)),
                ('condName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.createcond')),
            ],
        ),
    ]
