# Generated by Django 4.2 on 2023-04-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenderReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNo', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('clinteId', models.CharField(blank=True, max_length=255, null=True)),
                ('deadLineDate', models.DateField()),
                ('procure_method', models.CharField(max_length=255)),
                ('tender_status', models.CharField(max_length=255)),
                ('financial_value', models.CharField(max_length=255)),
            ],
        ),
    ]
