# Generated by Django 4.2 on 2023-04-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderCond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condOne', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='tenderreg',
            name='condOne',
        ),
        migrations.RemoveField(
            model_name='tenderreg',
            name='condThree',
        ),
        migrations.RemoveField(
            model_name='tenderreg',
            name='condTwo',
        ),
    ]
