# Generated by Django 4.2 on 2023-04-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderreg',
            name='category',
            field=models.CharField(default=16042023, max_length=255),
            preserve_default=False,
        ),
    ]
