# Generated by Django 4.2 on 2023-04-30 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('tender', '0002_remove_tendercond_condname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendercond',
            name='condName',
            field=models.ForeignKey(default=30042023, on_delete=django.db.models.deletion.DO_NOTHING, to='client.createcond'),
            preserve_default=False,
        ),
    ]
