# Generated by Django 4.2 on 2023-04-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_tenderreg_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderreg',
            name='tender_status',
            field=models.CharField(choices=[('Evaluated', 'Evaluated'), ('Bid Submission', 'Bid Submission'), ('Awarded', 'Awarded'), ('Canceled', 'Canceled')], max_length=255),
        ),
    ]
