# Generated by Django 4.2 on 2023-04-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0003_tendercond_condname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tendercond',
            old_name='condOne',
            new_name='condition',
        ),
    ]
