# Generated by Django 4.2 on 2023-04-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNo', models.CharField(max_length=255)),
                ('orgName', models.CharField(max_length=255)),
                ('orgCategory', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Government', 'Government')], max_length=255)),
            ],
        ),
    ]
