# Generated by Django 4.2 on 2023-04-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientDetails',
            new_name='ClientDetail',
        ),
    ]
