# Generated by Django 4.2 on 2023-04-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidderReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('tinNo', models.CharField(max_length=255)),
                ('companyRegNo', models.CharField(max_length=255)),
                ('vatNo', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('dictrict', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=255)),
                ('business', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('foreignInput', models.CharField(max_length=255)),
                ('employeeNum', models.CharField(max_length=255)),
            ],
        ),
    ]
